### ISSUE TITLE
single-end read

### ISSUE THREAD

**Issue by yunfeiguo** [WGLab/SeqMule#100]
fix the following code to make it accept single-ended fastq
    die "ERROR: number of FASTQ files for 1st and 2nd read pair must be equal!\n"
    if (@fq1_list && $#fq1_list != $#fq2_list);

**Comment by yunfeiguo** [comment]
possible fix (check /home/yunfeiguo/projects/data/try_juan/20151024_trybaidudata for whether it works)
die "ERROR: number of FASTQ files for 1st and 2nd read pair must be equal!\n"
if (@fq1_list && @fq1_list && $#fq1_list != $#fq2_list);

**Comment by kk86bioinfo** [comment]
Hi, I have try with the possible fix above, not working, still getting error when I define `-a normal.fastq -a2 tumor.fastq --platform IonTorrent` please advise how to perform single-end ion-torrent variant calling using SeqMule.

**Comment by kk86bioinfo** [comment]
I think I found the issue. The correct fix is `if (@fq1_list && @fq2_list && $#fq1_list != $#fq2_list);`
A typo for list2 in the possible fix. Now the pipeline seems to identify tumor.0.fastq correctly.

**Comment by yunfeiguo** [comment]
Thanks. This issue has been fixed.
