### ISSUE TITLE
missing index file

### ISSUE THREAD

**Issue by yunfeiguo** [WGLab/SeqMule#101]
Dear Sir/Madam,

We found a problem while runing the tutorial's command:

seqmule pipeline -a normal_R1.fastq -b normal_R2.fastq -prefix exomeData -threads 8 -rg READGROUP -e -advanced advanced_config -capture default

The error says it cannot find index files, where I could find those index files or how they have to look like?

The error:

Current version: 1.2.3
Reading configuration file...
Done
NOTICE: Commandline options will override advanced configuration.
NOTICE: Parsing global settings...
Done
NOTICE: use default BED file hg19_exome.bed
NOTICE: checking contig(chromosome) name consistency in /mnt/2ndHDD/Pipeline/SeqMule/SeqMule-master/bin/secondary/../../database/human_g1k_v37.fasta and /mnt/2ndHDD/Pipeline/SeqMule/SeqMule-master/misc/hg19_exome.bed.
NOTICE: use --no-check-chr to skip chromosome name checking
NOTICE: contig names in capture file and reference match with each other.
NOTICE: Input BED file detected, only variants in corresponding regions will be generated.
Checking Phred score scheme: exomeData_result/exomeData.0.fastq exomeData_result/exomeData.1.fastq
NOTICE: Analysis name: exomeData
NOTICE: Input is exome (or captured) sequencing data
NOTICE: BED file used for caculating coverage statistics and extracting variants: hg19_exome.bed
NOTICE: Readgroup : READGROUP_exomeData
NOTICE: Sequencing platform: ILLUMINA
NOTICE: Library : LIBRARY
NOTICE: Phred scoring scheme : 33
NOTICE: Reference genome build is hg19
NOTICE: dbsnp138 will be used for variant calling and recalibration.
NOTICE: Java memory usage is limited to 1750m
NOTICE: java executable path: java
NOTICE: Max number of processes: 8
NOTICE: /tmp will be used for storing temporary files
Generating script...
NOTICE: Analysis configuration log will be overwritten: exomeData.config
ERROR: bwamem index file(s) missing (/mnt/2ndHDD/Pipeline/SeqMule/SeqMule-master/bin/secondary/../../database/bwa/human_g1k_v37.fasta)
neurogenetica@neurogenetica-All-Series:/mnt/2ndHDD/Pipeline/Task 02 Seqmule/seqMule/snippets/basic/pipeline$

Thank you for your help!

Kind regards,

**Comment by yunfeiguo** [comment]
The output is:
 human_g1k_v37.fasta  index_bwa_human_g1k_v37.fasta.tar.gz

 I think the index_bwa_human_g1k_v37.fasta.tar.gz file has not finished to download or is corrupted, I cannot untar it either, (tar: Unexpected EOF inarchive). The initial download process (seqmule download -down hg19all) might not work properly, some downloads get interrupted and do not restart, just jump to the next step.

 I tried several times to do the whole download of all documents.

 Is there a download-link or command so I can download individual files, like index_bwa_human_g1k_v37.fasta.tar.gz? What else files need to be in the bwa folder?

 Otherwise what could be the problem?

 Thank you!

**Comment by cenielyj** [comment]
I have the same problem, in China it is really hard to download such big file.
Have you fixed the problem? In the furture if I have downloaded it, I will upload into Baiduyun.
Keep in touch.

**Comment by yunfeiguo** [comment]
Did you solve the problem?

The files can be downloaded here: http://www.openbioinformatics.org/seqmule/hg_index/

After you download these files, put them in 'seqmule/database' (assume seqmule/ is your installation path) and unzip them. For index files, you need to create subdirectories (e.g. bwa for bwa index). In the end, you should see the following file structure:



```
database/
|-- 1000G_omni2.5.b37.vcf
|-- 1000G_omni2.5.b37.vcf.idx
|-- bowtie
|   |-- human_g1k_v37.1.ebwt
|   |-- human_g1k_v37.2.ebwt
|   |-- human_g1k_v37.3.ebwt
|   |-- human_g1k_v37.4.ebwt
|   |-- human_g1k_v37.rev.1.ebwt
|   `-- human_g1k_v37.rev.2.ebwt
|-- bowtie2
|   |-- human_g1k_v37.1.bt2
|   |-- human_g1k_v37.2.bt2
|   |-- human_g1k_v37.3.bt2
|   |-- human_g1k_v37.4.bt2
|   |-- human_g1k_v37.rev.1.bt2
|   `-- human_g1k_v37.rev.2.bt2
|-- bwa
|   |-- human_g1k_v37.fasta -> /home/yunfeiguo/projects/seqmule_working/bin/secondary/../../database/human_g1k_v37.fasta
|   |-- human_g1k_v37.fasta.amb
|   |-- human_g1k_v37.fasta.ann
|   |-- human_g1k_v37.fasta.bwt
|   |-- human_g1k_v37.fasta.fai
|   |-- human_g1k_v37.fasta.pac
|   |-- human_g1k_v37.fasta.sa
|   `-- index_bwa_human_g1k_v37.fasta.tar.gz
|-- dbsnp_hg19_138.vcf
|-- dbsnp_hg19_138.vcf.idx
|-- hapmap_3.3.b37.vcf
|-- hapmap_3.3.b37.vcf.idx
|-- hg19agilent
|   |-- hg19_HaloPlex_Cancer_Research_Panel_illumina.bed
|   |-- hg19_HaloPlex_Cancer_Research_Panel_iontorrent.bed
|   |-- hg19_HaloPlex_Exome.bed
|   |-- hg19_HaloPlex_ICCG_iontorrent.bed
|   |-- hg19_SureSelect_Human_All_Exon_50Mb.bed
|   |-- hg19_SureSelect_Human_All_Exon_V1.bed
|   |-- hg19_SureSelect_Human_All_Exon_V2.bed
|   |-- hg19_SureSelect_Human_All_Exon_V4.bed
|   |-- hg19_SureSelect_Human_All_Exon_V4_UTRs.bed
|   |-- hg19_SureSelect_Human_All_Exon_V5.bed
|   |-- hg19_SureSelect_Human_All_Exon_V5_UTRs.bed
|   |-- hg19_SureSelect_Human_Kinome_V1.bed
|   `-- hg19_SureSelect_Human_Methyl_Seq.bed
|-- hg19iontorrent
|   |-- hg19_iontorrent_AmpliSeq_CancerHotspot.bed
|   |-- hg19_iontorrent_AmpliSeq_CancerPrimer.bed
|   |-- hg19_iontorrent_AmpliSeq_CompCancer.bed
|   |-- hg19_iontorrent_AmpliSeq_Exome.bed
|   `-- hg19_iontorrent_AmpliSeq_InheritDisease.bed
|-- hg19nimblegen
|   |-- hg19_nimblegen_SeqCap_exome_v2.bed
|   |-- hg19_nimblegen_SeqCap_exome_v2.bed.original
|   |-- hg19_nimblegen_SeqCap_exome_v3.bed
|   |-- hg19_nimblegen_SeqCap_exome_v3.bed.original
|   |-- hg19_nimblegen_SeqCap_EZ_50Mb_UTR.bed
|   |-- hg19_nimblegen_SeqCap_EZ_50Mb_UTR.bed.original
|   |-- hg19_nimblegen_SeqCap_EZ_comprehensive_cancer.bed
|   |-- hg19_nimblegen_SeqCap_EZ_comprehensive_cancer.bed.original
|   |-- hg19_nimblegen_SeqCap_EZ_MHC.bed
|   |-- hg19_nimblegen_SeqCap_EZ_MHC.bed.original
|   |-- hg19_nimblegen_SeqCap_EZ_neuro_panel.bed
|   `-- hg19_nimblegen_SeqCap_EZ_neuro_panel.bed.original
|-- human_g1k_v37.dict
|-- human_g1k_v37.fasta
|-- human_g1k_v37.fasta.fai
|-- Mills_and_1000G_gold_standard.indels.b37.vcf
|-- Mills_and_1000G_gold_standard.indels.b37.vcf.idx
|-- snap
|   |-- human_g1k_v37.fasta
|   |   |-- Genome
|   |   |-- GenomeIndex
|   |   |-- GenomeIndexHash
|   |   `-- OverflowTable
|   `-- index_snap_human_g1k_v37.fasta.tar.gz
`-- soap
    |-- human_g1k_v37.fasta.index.amb
    |-- human_g1k_v37.fasta.index.ann
    |-- human_g1k_v37.fasta.index.bwt
    |-- human_g1k_v37.fasta.index.fmv
    |-- human_g1k_v37.fasta.index.hot
    |-- human_g1k_v37.fasta.index.lkt
    |-- human_g1k_v37.fasta.index.pac
    |-- human_g1k_v37.fasta.index.rev.bwt
    |-- human_g1k_v37.fasta.index.rev.fmv
    |-- human_g1k_v37.fasta.index.rev.lkt
    |-- human_g1k_v37.fasta.index.rev.pac
    |-- human_g1k_v37.fasta.index.sa
    |-- human_g1k_v37.fasta.index.sai
```

Another way to download files without keeping the terminal open all the time: use 
```
nohup seqmule download -hg19all &
```

**Comment by cenielyj** [comment]
thanks very much
we have download all the files and thabks to the file structure
we are now running the first seqmule pipeline
thanks again i will keep you posted and promote seqmule in china
best wishes

Dr. Yijia Li
0478189761

在 2016年1月31日，03:15，Yunfei Guo <notifications@github.com<mailto:notifications@github.com>> 写道：


Did you solve the problem?

The files can be downloaded here: http://www.openbioinformatics.org/seqmule/hg_index/

After you download these files, put them in 'seqmule/database' (assume seqmule/ is your installation path) and unzip them. For index files, you need to create subdirectories (e.g. bwa for bwa index). In the end, you should see the following file structure:

database/
|-- 1000G_omni2.5.b37.vcf
|-- 1000G_omni2.5.b37.vcf.idx
|-- bowtie
|   |-- human_g1k_v37.1.ebwt
|   |-- human_g1k_v37.2.ebwt
|   |-- human_g1k_v37.3.ebwt
|   |-- human_g1k_v37.4.ebwt
|   |-- human_g1k_v37.rev.1.ebwt
|   `-- human_g1k_v37.rev.2.ebwt
|-- bowtie2
|   |-- human_g1k_v37.1.bt2
|   |-- human_g1k_v37.2.bt2
|   |-- human_g1k_v37.3.bt2
|   |-- human_g1k_v37.4.bt2
|   |-- human_g1k_v37.rev.1.bt2
|   `-- human_g1k_v37.rev.2.bt2
|-- bwa
|   |-- human_g1k_v37.fasta -> /home/yunfeiguo/projects/seqmule_working/bin/secondary/../../database/human_g1k_v37.fasta
|   |-- human_g1k_v37.fasta.amb
|   |-- human_g1k_v37.fasta.ann
|   |-- human_g1k_v37.fasta.bwt
|   |-- human_g1k_v37.fasta.fai
|   |-- human_g1k_v37.fasta.pac
|   |-- human_g1k_v37.fasta.sa
|   `-- index_bwa_human_g1k_v37.fasta.tar.gz
|-- dbsnp_hg19_138.vcf
|-- dbsnp_hg19_138.vcf.idx
|-- hapmap_3.3.b37.vcf
|-- hapmap_3.3.b37.vcf.idx
|-- hg19agilent
|   |-- hg19_HaloPlex_Cancer_Research_Panel_illumina.bed
|   |-- hg19_HaloPlex_Cancer_Research_Panel_iontorrent.bed
|   |-- hg19_HaloPlex_Exome.bed
|   |-- hg19_HaloPlex_ICCG_iontorrent.bed
|   |-- hg19_SureSelect_Human_All_Exon_50Mb.bed
|   |-- hg19_SureSelect_Human_All_Exon_V1.bed
|   |-- hg19_SureSelect_Human_All_Exon_V2.bed
|   |-- hg19_SureSelect_Human_All_Exon_V4.bed
|   |-- hg19_SureSelect_Human_All_Exon_V4_UTRs.bed
|   |-- hg19_SureSelect_Human_All_Exon_V5.bed
|   |-- hg19_SureSelect_Human_All_Exon_V5_UTRs.bed
|   |-- hg19_SureSelect_Human_Kinome_V1.bed
|   `-- hg19_SureSelect_Human_Methyl_Seq.bed
|-- hg19iontorrent
|   |-- hg19_iontorrent_AmpliSeq_CancerHotspot.bed
|   |-- hg19_iontorrent_AmpliSeq_CancerPrimer.bed
|   |-- hg19_iontorrent_AmpliSeq_CompCancer.bed
|   |-- hg19_iontorrent_AmpliSeq_Exome.bed
|   `-- hg19_iontorrent_AmpliSeq_InheritDisease.bed
|-- hg19nimblegen
|   |-- hg19_nimblegen_SeqCap_exome_v2.bed
|   |-- hg19_nimblegen_SeqCap_exome_v2.bed.original
|   |-- hg19_nimblegen_SeqCap_exome_v3.bed
|   |-- hg19_nimblegen_SeqCap_exome_v3.bed.original
|   |-- hg19_nimblegen_SeqCap_EZ_50Mb_UTR.bed
|   |-- hg19_nimblegen_SeqCap_EZ_50Mb_UTR.bed.original
|   |-- hg19_nimblegen_SeqCap_EZ_comprehensive_cancer.bed
|   |-- hg19_nimblegen_SeqCap_EZ_comprehensive_cancer.bed.original
|   |-- hg19_nimblegen_SeqCap_EZ_MHC.bed
|   |-- hg19_nimblegen_SeqCap_EZ_MHC.bed.original
|   |-- hg19_nimblegen_SeqCap_EZ_neuro_panel.bed
|   `-- hg19_nimblegen_SeqCap_EZ_neuro_panel.bed.original
|-- human_g1k_v37.dict
|-- human_g1k_v37.fasta
|-- human_g1k_v37.fasta.fai
|-- Mills_and_1000G_gold_standard.indels.b37.vcf
|-- Mills_and_1000G_gold_standard.indels.b37.vcf.idx
|-- snap
|   |-- human_g1k_v37.fasta
|   |   |-- Genome
|   |   |-- GenomeIndex
|   |   |-- GenomeIndexHash
|   |   `-- OverflowTable
|   `-- index_snap_human_g1k_v37.fasta.tar.gz
`-- soap
    |-- human_g1k_v37.fasta.index.amb
    |-- human_g1k_v37.fasta.index.ann
    |-- human_g1k_v37.fasta.index.bwt
    |-- human_g1k_v37.fasta.index.fmv
    |-- human_g1k_v37.fasta.index.hot
    |-- human_g1k_v37.fasta.index.lkt
    |-- human_g1k_v37.fasta.index.pac
    |-- human_g1k_v37.fasta.index.rev.bwt
    |-- human_g1k_v37.fasta.index.rev.fmv
    |-- human_g1k_v37.fasta.index.rev.lkt
    |-- human_g1k_v37.fasta.index.rev.pac
    |-- human_g1k_v37.fasta.index.sa
    |-- human_g1k_v37.fasta.index.sai


Another way to download files without keeping the terminal open all the time: use

nohup seqmule download -hg19all &


―

**Comment by yunfeiguo** [comment]
Glad to hear that! Thank you.

**Comment by rashidma** [comment]
Hi Yun,
I recently run seqmule in quick mode with the following commands to test the installation-
` seqmule pipeline -a normal_R1.fastq.gz -b normal_R2.fastq.gz -prefix example -N 2 -capture default -threads 10 -e`
The report I got is matched with http://www.openbioinformatics.org/seqmule/example/example_report/example/example.html
There are differences that I assume due to the target region from bed file. In my run the bed is -
hg19_exonPlus5bp_UCSCrefGene.bed
But on your website the bed is hg19_exome.bed
Can you provide that hg19_exome.bed
Please comment overall.
Regards
Mamoon
