### ISSUE TITLE
clean directory for seqmule update

### ISSUE THREAD

**Issue by kaichop** [WGLab/SeqMule#115]
When I update to latest version with 'git pull', then run seqmule, I got the following message

-----------------------------UPDATE AVAILABLE---------------------------------
------------------------------------------------------------------------------
RECOMMEND: run 'seqmule update'
ALTERNATIVE: download from 'http://www.openbioinformatics.org/seqmule' and unzip it to 
/share/apps/SeqMule/bin/secondary
to overwrite old stuff
------------------------------------------------------------------------------
------------------------------------------------------------------------------

The http://www.openbioinformatics.org/seqmule has a lot of outdated or irrelevant files or files that should not be made available online.

**Comment by yunfeiguo** [comment]
Thanks for your comments! I have removed unnecessary files on http://www.openbioinformatics.org/seqmule. The remaining files are for docs or download.

Regarding the update, could you point me to your seqmule folder?
