### ISSUE TITLE
gatk error at step 7.

### ISSUE THREAD

**Issue by anilkanthi** [WGLab/SeqMule#123]
Error while running the command : 
**seqmule pipeline -a 62273470_S23_R1_001.fastq.gz -b 62273470_S23_R2_001.fastq.gz -prefix example -N 2 -capture default -threads 4 -e **

[example.script.txt](https://github.com/WGLab/SeqMule/files/184152/example.script.txt)
[example.config.txt](https://github.com/WGLab/SeqMule/files/184153/example.config.txt)
[example.log.txt](https://github.com/WGLab/SeqMule/files/184154/example.log.txt)

##### ERROR stack trace 
java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:160)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:53)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:54)
	at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:90)
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:77)
	... 4 more
##### ERROR ------------------------------------------------------------------------------------------

----------ERROR----------
[ => SeqMule Execution Status: step 7 FAILED at Tue Mar 22 18:45:24 IST 2016, gatklite realn]
ERROR: command failed
/home/genetics/Documents/anil/SeqMule-master/bin/secondary/../../bin/secondary/worker /home/genetics/Desktop/sidram/seqmule.03222016.4991.logs 7 "/home/genetics/Documents/anil/SeqMule-master/bin/secondary/../../bin/secondary/runGATKLITEREALN -advanced example.config -n 6 -ref /home/genetics/Documents/anil/SeqMule-master/bin/secondary/../../database/human_g1k_v37.fasta -java java -jmem 1750m -gatk /home/genetics/Documents/anil/SeqMule-master/exe/gatklite/GenomeAnalysisTKLite.jar -threads 4 -gatk-nt 2 --tmpdir /tmp  -bed /home/genetics/Documents/anil/SeqMule-master/misc/hg19_exonPlus5bp_UCSCrefGene.bed -goldindel /home/genetics/Documents/anil/SeqMule-master/bin/secondary/../../database/Mills_and_1000G_gold_standard.indels.b37.vcf  -dbsnp /home/genetics/Documents/anil/SeqMule-master/bin/secondary/../../database/dbsnp_hg19_138.vcf  -samtools /home/genetics/Documents/anil/SeqMule-master/exe/samtools/samtools  -pl ILLUMINA  -bam example_result/example.0_bwamem.sort.rmdup.readfiltered.bam -out example_result/example.0_bwamem.sort.rmdup.readfiltered.realn.bam "
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
After fixing the problem, please execute 'cd /home/genetics/Desktop/sidram' and 'seqmule run example.script' to resume analysis.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by yunfeiguo** [comment]
Hi,

Have you looked at the FAQ?

http://doc-openbio.readthedocs.org/projects/seqmule/en/latest/Miscellaneous/FAQ/#how-to-solve-the-javalangnullpointerexception-problem

**Comment by anilkanthi** [comment]
Thank you so much!!! I have been trying to get over this issue since yesterday and now it has resumed, after I changed the default java -version to 1.7! Thanks again.

**Comment by yunfeiguo** [comment]
Glad to hear that:)
