### ISSUE TITLE
Seqmule successfully   tested on Red hat Enterprise Linux (RHEL ) version 5.4

### ISSUE THREAD

**Issue by Amjadhpc** [WGLab/SeqMule#144]
Red hat Enterprise Linux  comes with default g++ compiler version  4.1.2.

Seqmule requires g++ version 4.6.3 or 4.4.7.
Following Steps  show how to satisfy this requirement  for  RHEL 5.4

1. **Getting g++ 4.7**
Third party repo provides g++ 4.6.3 for Centos 5.X.
https://people.centos.org/tru/devtools/5/x86_64/RPMS/

I downloaded and installed the following  RPMS from the above repo.

devtoolset-1.0-binutils-2.22.52.0.1-10.el5.x86_64.rpm
devtoolset-1.0-binutils-devel-2.22.52.0.1-10.el5.x86_64.rpm
devtoolset-1.0-build-1-3.el5.noarch.rpm
devtoolset-1.0-gcc-4.7.0-5.2.el5.centos.x86_64.rpm
devtoolset-1.0-gcc-c++-4.7.0-5.2.el5.centos.x86_64.rpm
devtoolset-1.0-libstdc++-devel-4.7.0-5.2.el5.centos.x86_64.rpm
devtoolset-1.0-runtime-1-3.el5.noarch.rpm
scl-utils-20120229-1.el5.centos.x86_64.rpm

In addition downloaded and installed   libgomp  rpm
libgomp-4.4.7-1.el5.x86_64.rpm

I executed the following command to install the rpms in default location,

rpm -ivh <packagename> .

2. **Adding g++ in path**

  I added the path of g++ in enviroment variable PATH. 
 export PATH=/opt/devtools/devtoolset-1.0/root/usr/bin/:$PATH
This will make  g++ 4.7 as default g++ compiler while building seqmule.

3. **Building Seqmule**
 As shown in the website just run the  ./Build all script from Seqmule root directory. and all packages requested will be installed.

4. **Running Seqmule**
   Add java 1.7.0 in PATH environment variable to get  seqmule running.

**Comment by yunfeiguo** [comment]
Thanks, Amjad! Nice detailed steps!
