### ISSUE TITLE
can we use SeqMule for mouse as non-default genome

### ISSUE THREAD

**Issue by yatpat** [WGLab/SeqMule#164]
Hi,
I am trying to run seqmule for mouse as non-default genome. 
I have downloaded the mouse genome , dbSNP and indel database and carried out the respective indexing.
By using advanced_config, changing the options giving the path for reference genome, dbSNP, when I run, its always looking Mills and 1000G indel gold standard SNP database. 

See below the config file for bwa_gatk_HaplotypeCaller_samtools.config - showing some part 

#Global settings (these settings will be overriden by command line options)
go_threads=12 #number of threads for parallel alignment 
go_platform=0 #sequencer name (one value for all input or comma-separated list)
go_lb=0 #library name(one value for all input or comma-separated list) 
go_phred=1 #choose Phred quality score encoding scheme. 1 for auto-detection, 33 for for Sanger, Illumina 1.8+ FASTQ file and 64 for Solexa, Illumina 1.3+, 1.5+ FASTQ file
go_rg=sample11 #specify readgroup (one value for all input or comma-separated list)
go_ref=Mus_musculus.GRCm38.dna.primary_assembly.fa #reference genome file name. It should be specified with full path for robustness
go_capture=0 #capture region file
go_dbsnp=mgp.v5.merged.snps_all.dbSNP142.vcf #dbSNP file for GATK only
go_hapmap=0 #HapMap file for GATK
go_dbsnpver=142 #dbSNP version for variant recalibration and annotation, default is 137
go_kg=0 #1000 Genome project VCF file
go_buildver=0 #genome build version, default is hg19
go_index=0 #index prefix for all alignment programs. This will be omitted if a program-specific index prefix is supplied
go_bowtie=0 #index prefix for bowtie
go_bowtie2=0 #index prefix for bowtie2
go_soap=0 #index prefix for soap
go_jmem= #max java memory
go_gatknt=12 #number of threads for GATK
go_tmpdir=tmpDir #folder for holding temporary data

Giving error - which I dont want to use it for mouse analysis
ERROR: No Mills and 1000G indel database in /~tools/seqMule/SeqMule-master/bin/secondary/../../database

Please let me know how to solve this .

Thanks

**Comment by yunfeiguo** [comment]
Hi @yatpat 
yes, you can use non-human ref. Please use `--indel` option (on command line) for the missing indel database.

**Comment by yatpat** [comment]
Thanks. 
It is working after giving path for mouse indel database to --indel (on command line)

But, when I disable the parameter for "go_kg=0 #1000 Genome project VCF file or o nthe command line --kg 0", still it s finding for 1000g vcf file(which is actually not for mouse) and it is giving error "ERROR: No 1000g database in ~/database"  and it is same for hapmap parameter.

Please let me know for the same.

**Comment by yunfeiguo** [comment]
all 3 databases, indel, hapmap, dbsnp are used for GATK's VQSR variant filtering. It's a all-or-none scenario. If you don't have all 3 databases, you can disable VQSR altogether in `advanced_config` (force hard filtering).

**Comment by yatpat** [comment]
Yes, I have given all three database(dbsnp,indel and hapmap vcf.gz files), here is my seqmule command

seqmule pipeline -a ~/test_1.fq -b ~/test_2.fq -g -ref ~/seqMule/SeqMule-master/database/bwa/Mus_musculus.GRCm38.dna.primary_assembly.fa -t 8 -p BwaGatkSamtools --readgroup sample11 --dbsnp ~/seqMule/SeqMule-master/database/mgp.v5.merged.snps_all.dbSNP142.vcf.gz.md5 --dbsnpver 142 --indel ~/seqMule/SeqMule-master/database/mgp.v5.merged.indels.dbSNP142.normed.vcf.gz --hapmap ~/seqMule/SeqMule-master/database/Merged_Hapmap_WT_Genotypes.txt.gz --gatknt 8 --tmpdir ~/tmpDir --advanced bwa_gatk_HaplotypeCaller_samtools_new.config

with --kg=0
and I set 1 to VQSR for dbsnp and indel for gatk, not hard filtering for both at the same time.

o_gatk_forceSNPVQSR=1 #if set to 1, force using VQSR (a better filtering method) on SNP, otherwise seqmule use VQSR only if BAM size is larger than 1GB. CAUTION: if number of variants  is too small, VQSR doesn't work.
o_gatk_forceSNPHardFilter=0 #if set to 1, force using hard filtering on SNP, otherwise seqmule use VQSR only if BAM size is larger than 1GB. CAUTION: do NOT set o_gatk_forceSNPVQSR and o_gatk_forceSNPHardFilter both to 1!
o_gatk_forceINDELVQSR=1 #if set to 1, force using VQSR (a better filtering method) on INDEL, otherwise seqmule use VQSR only if BAM size is larger than 15GB. CAUTION: if number of variants  is too small, VQSR doesn't work.
o_gatk_forceINDELHardFilter=0 #if set to 1, force using hard filtering on INDEL, otherwise seqmule use VQSR only if BAM size is larger than 15GB. CAUTION: do NOT set o_gatk_forceINDELVQSR and o_gatk_forceINDELHardFilte both to 1!

 
After running this command. Its again looking for 1000g vcf file.  
ERROR: "No 1000g database in ~/database"

Is that I am missing to set any parameter in seqmule or in config file?

Thanks

**Comment by yunfeiguo** [comment]
actually `kg` is also needed by GATK VQSR. One workaround is that use same file for both `hapmap` and `kg`, or more ideally, find another database file that has high quality variant calls.

**Comment by yatpat** [comment]
Thanks.
Its working after giving same file for hapmap and kg.
It will be easier to give all these parameter optional(except dbsnp) other than human.
For other organisms, user can mention organism as parameter in seqmule so that hapmap,indel and kg parameter becomes optional.

**Comment by yunfeiguo** [comment]
Great! Thanks for the suggestion.
