### ISSUE TITLE
Trying to delete NOTICE: Reference genome build is hg 19  and NOTICE: dbsnp138 will be used for variant calling and recalibration , when we run seqmule for other specie non-human 

### ISSUE THREAD

**Issue by juanmluque** [WGLab/SeqMule#176]
Hi Yunfei,
As you know , we are trying to apply SeqMule for Arabidopsis thaliana, and we would like to delete the messages:
NOTICE: Reference genome build is hg 19               and 
NOTICE: dbsnp138 will be used for variant calling and recalibration
when pipeline starts (or to change the message about hg 19 by  other reference genome build).
We have changed the next parameters:
go_dbsnp=0 #dbSNP file for GATK only
go_hapmap=0 #HapMap file for GATK
go_dbsnpver=0 #dbSNP version for variant recalibration and annotation, default is 137
go_kg=0 #1000 Genome project VCF file
go_buildver=0 #genome build version, default is hg19
and also:
o_gatklite_forceSNPHardFilter=1 #if set to 1, force using hard filtering on SNP, otherwise seqmule use VQSR only if BAM size is larger than 1GB. CAUTION: do NOT set o_gatklite_forceSNPVQSR and o_gatklite_forceSNPHardFilter both to 1!
and:
o_gatklite_forceINDELHardFilter=1 #if set to 1, force using hard filtering on INDEL, otherwise seqmule use VQSR only if BAM size is larger than 15GB. CAUTION: do NOT set o_gatklite_forceINDELVQSR and o_gatklite_forceINDELHardFilte both to 1!

But the NOTICE messages are the same again (hg19 and dbsnp 138) when we run the pipeline.

Please, what can we do to solve this?
Thank you very much.
Best.
Juan M.

**Comment by yunfeiguo** [comment]
Hi @juanmluque 
I have disabled genome build notice when you use your custom reference genome. For dbsnp, it's more involved so for now I just added a qualifier, e.g. "if enabled, dbsnp137 will be used ...".

If you got SeqMule via zip file, you can get the updated version here: https://github.com/yunfeiguo/SeqMule/archive/issue176.zip
if you don't want to reinstall, you can copy the unzipped folder and overwrite your old version.

If you got SeqMule via git, you can do
```
git remote add yg_fork git@github.com:yunfeiguo/SeqMule.git
git pull yg_fork
git checkout yg_fork/issue176
```

Thanks.
