### ISSUE TITLE
Mac OS catalina: I could not install databases 

### ISSUE THREAD

**Issue by hawkibo** [WGLab/SeqMule#177]
hi,

When I run the command:
seqmule download -down hg19all
it cannot download the databases, some parts are missing (it should be 5.2 gb but it is 1.6 gb somehow)
Either it gives the error: there is no database did you download?
or it says 'md5 checksum' error. 
I tried it with ubuntu, Debian and even windows subsystem linux(ubuntu) and there was no problem.

Did you try SeqMule with Mac OS? Can you please help me with the commands? Thanks

**Comment by yunfeiguo** [comment]
Hi @hawkibo please update seqmule (via `git`) and try again. The macOS `tar` has different commandline options than GNU `tar` and therefore it caused problems. Thanks.

**Comment by hawkibo** [comment]
I have updated seqmule. When I run the command:
seqmule download -down hg19all
It still says:
MD5 check...
Cannot find md5sum to check MD5 hash...
MD5 doesn't match
then it delete the file:(
IS there any other way for me to download databases?

**Comment by hawkibo** [comment]
I manually installed md5sum. it looks ok for now

**Comment by yunfeiguo** [comment]
Glad you made it work. Apparently my mac has been tainted with `md5sum`.

**Comment by hawkibo** [comment]
I made some progress since, after I run the code:
'perl seqmule pipeline -a normal_R1.fastq -b normal_R2.fastq -prefix example -N 2 -capture default -threads 16 -e -q -v -phred 33' 
for example files, it stops at this point:
"
/tmp/seqmule8470.517307691511580564841script: line 4: /Users/hawkibo/SeqMule/exe/freebayes/bin/freebayes.dSYM/Contents/Resources/DWARF/freebayes: cannot execute binary file


----------ERROR----------
[ => SeqMule Execution Status: step 41 FAILED at Sat Feb  1 16:47:22 +03 2020, freebayes variant calling]
ERROR: command failed
"
I thought that it should be due to freebayes and I downloaded it and run 'make' manually and separately, but I could not pass this point. When I run freebayes separately it works perfectly. What can I do for a solution? Thanks

**Comment by hawkibo** [comment]
For freebayes:
I downloaded separately and run 'make'. Then it produced freebayes.dSYM file; but when you build freebayes inside seqmule it does not produce. Then I put freebayes.dSYM inside seqmule/exe/freebayes/bin. Since they are not the same versions of freebayes it will not work, you need seqmule version of freebayes. So I put seqmule/exe/freebayes/bin/freebayes inside freebayes.dSYM file. And then it began to work.
Now I have problem in this step:
"
Extracting variants based on specified BED file.
NOTICE:        0 extracted variants written to example_result/example.0_bwamem.sort.rmdup.readfiltered.realn.0_gatklite.extract.vcf
Generating variant stats
Cannot read output from vcf-stats: Broken VCF header, no column names?
 at /Users/hawkibo/SeqMule/exe/vcftools/perl/../perl/Vcf.pm line 172.
	Vcf::throw('VcfStats=HASH(0x7fc1fd0189f8)', 'Broken VCF header, no column names?') called at /Users/hawkibo/SeqMule/exe/vcftools/perl/../perl/Vcf.pm line 865
	VcfReader::_read_column_names('VcfStats=HASH(0x7fc1fd0189f8)') called at /Users/hawkibo/SeqMule/exe/vcftools/perl/../perl/Vcf.pm line 600
	VcfReader::parse_header('VcfStats=HASH(0x7fc1fd0189f8)') called at /Users/hawkibo/SeqMule/exe/vcftools/perl/../perl/VcfStats.pm line 53
	VcfStats::parse_header('VcfStats=HASH(0x7fc1fd0189f8)') called at /Users/hawkibo/SeqMule/exe/vcftools/perl/vcf-stats line 137
	main::vcf_stats('HASH(0x7fc1fd003128)') called at /Users/hawkibo/SeqMule/exe/vcftools/perl/vcf-stats line 12

INFO  10:29:13,899 SelectVariants - 5 records processed. 
INFO  10:29:13,939 ProgressMeter -            done        5.00e+00    0.5 s       25.3 h     27.2%         1.7 s     1.2 s 
INFO  10:29:13,939 ProgressMeter - Total runtime 0.46 secs, 0.01 min, 0.00 hours 


----------ERROR----------
[ => SeqMule Execution Status: step 59 FAILED at Thu Feb  6 11:29:14 +03 2020, Extract variants in custom regions]
ERROR: command failed
/Users/hawkibo/SeqMule/bin/secondary/../../bin/secondary/worker /Users/hawkibo/SeqMule/bin/seqmule.02062020.52977.logs 59 "/Users/hawkibo/SeqMule/bin/secondary/../../bin/seqmule stats -tmpdir /var/folders/n1/lbjmxnx574l_5jm81fv01fkh0000gn/T/  -capture /Users/hawkibo/SeqMule/misc/hg19_exonPlus5bp_UCSCrefGene.bed  -vcf example_result/example.0_bwamem.sort.rmdup.readfiltered.realn.0_gatklite.vcf -p example_result/example.0_bwamem.sort.rmdup.readfiltered.realn.0_gatklite"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
After fixing the problem, please execute 'cd /Users/hawkibo/SeqMule/bin' and 'seqmule run example.script' to resume analysis.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
"
I modified vcf and vcf.gz file and indexed them manually but it does not work. Can you help me please?
